AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ProcessCSVFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.lambda_handler
      Runtime: python3.11
      CodeUri: lambdas/process_csv/
      Environment:
        Variables:
          DYNAMODB_TABLE: expenses
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type'"
              AllowOrigin: "'*'"

  GetSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.lambda_handler
      Runtime: python3.11
      CodeUri: lambdas/get_summary/
      Environment:
        Variables:
          DYNAMODB_TABLE: expenses
      Events:
        GetAllSummary:
          Type: Api
          Properties:
            Path: /summary
            Method: get
            Cors:
              AllowMethods: "'GET,OPTIONS'"
              AllowHeaders: "'Content-Type'"
              AllowOrigin: "'*'"
        GetSummaryByUserId:
          Type: Api
          Properties:
            Path: /summary/{user_id}
            Method: get
            Cors:
              AllowMethods: "'GET,OPTIONS'"
              AllowHeaders: "'Content-Type'"
              AllowOrigin: "'*'"